"""Types module for streamlit-lightweight-charts."""

from streamlit_lightweight_charts_pro.type_definitions.colors import (
    Background,
    BackgroundGradient,
    BackgroundSolid,
)
from streamlit_lightweight_charts_pro.type_definitions.enums import (
    AnnotationPosition,
    AnnotationType,
    ChartType,
    ColorType,
    ColumnNames,
    CrosshairMode,
    HorzAlign,
    LastPriceAnimationMode,
    LineStyle,
    LineType,
    MarkerPosition,
    MarkerShape,
    PriceScaleMode,
    TrackingActivationMode,
    TrackingExitMode,
    TradeType,
    TradeVisualization,
    VertAlign,
)
from streamlit_lightweight_charts_pro.type_definitions.protocols import (
    AnnotationProtocol,
    ChartData,
    ChartDataProtocol,
    ChartOptions,
    ChartOptionsProtocol,
    ChartProtocol,
    MarkerProtocol,
    NumericValue,
    SeriesProtocol,
    TimeSeriesDataProtocol,
    TimeValue,
    TooltipProtocol,
    TradeProtocol,
    VisualizationOptionsProtocol,
)

__all__ = [
    # Enums
    "AnnotationPosition",
    "AnnotationType",
    "ChartType",
    "ColorType",
    "LineStyle",
    "LineType",
    "CrosshairMode",
    "MarkerPosition",
    "MarkerShape",
    "PriceScaleMode",
    "LastPriceAnimationMode",
    "HorzAlign",
    "VertAlign",
    "TrackingExitMode",
    "TrackingActivationMode",
    "ColumnNames",
    "TradeType",
    "TradeVisualization",
    # Colors
    "Background",
    "BackgroundSolid",
    "BackgroundGradient",
    # Protocols
    "ChartDataProtocol",
    "TimeSeriesDataProtocol",
    "ChartOptionsProtocol",
    "SeriesProtocol",
    "ChartProtocol",
    "MarkerProtocol",
    "TradeProtocol",
    "AnnotationProtocol",
    "TooltipProtocol",
    "VisualizationOptionsProtocol",
    # Type aliases
    "ChartData",
    "ChartOptions",
    "TimeValue",
    "NumericValue",
]
